name = "nova_lab/nova_core"
version = "0.6.0"
description = "A filesystem-based web framework for Luau runtimes, with out-of-the-box support for Lute, Lune and Zune."
authors = ["Hypernova Lab (https://github.com/hypernova-lab)"]
license = "MIT"
repository = "https://github.com/hypernova-lab/nova"
private = false
includes =[
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**/*.luau",
]

[target]
environment = "luau"
lib = "src/index.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
