name = "nova/core"
version = "0.6.0"
description = "A convention-driven, runtime-agnostic web framework for Luau."
authors = ["Hypernova Lab (https://github.com/hypernova-lab)"]
license = "MIT"
repository = "https://github.com/hypernova-lab/nova"
private = false
includes =[
    "pesde.toml",
    "README.md",
    "LICENSE",
    "src/**/*.luau",
]

[target]
environment = "luau"
lib = "src/index.luau"

[indices]
default = "https://github.com/pesde-pkg/index"
